export default {
	// 门店管理
	storeEdit: '/store/edit',
	storeAdd: '/store/storeAdd',
	storeEdit: '/store/storeEdit',
	storeRemove: '/store/storeRemove',
	storeChange: '/store/storeOne',
	storeInfo: '/store/storeInfo',
	storeDownload: '/store/storeDownload',
	storeImport: '/store/storeImport',
	storeExplode: '/store/storeExplode',
	storeBatchModification: '/store/storeBatchModification',
	storeWeixinQrcode: '/store/storeWeixinQrcode',
	appletQrcode: '/store/appletQrcode',
	storeReply: '/store/storeReply',
	storeCodeDown: '/store/storeCodeDown',
	storeCodeList: '/store/codelist',
	storeHomePageEdit: '/store/homePageEdit',

	// 导购管理
	staffList: '/staff/list',
	staffEdit: '/staff/edit',
	staffAdd: '/staff/add',
	staffRemove: '/staff/remove',
	staffStationList: '/staff/stationList',
	staffStationAdd: '/staff/stationAdd',
	staffStationEdit: '/staff/stationEdit',
	staffCodeList: '/staff/staffCodeList',
	staffReply: '/staff/staffReply',
	staffBgList: '/staff/staffBgList',
	staffBgSave: '/staff/staffBgSave',
	// 区域列表
	channelAreaList: '/channel/list',
	channelAdd: '/channel/add',
	channelEdit: '/channel/edit',
	channelRemove: '/channel/remove',
	shiftstorelist: '/channel/shiftstorelist',
	channelShift: '/channel/shift',
	// 导购组设置
	shopSettingList: '/shoppers/settingList',
	shopSettingAdd: '/shoppers/settingAdd',
	shopSettingEdit: '/shoppers/settingEdit',
	shopSettingRemove: '/shoppers/settingRemove',
	shopSettingImport: '/shoppers/settingImport',
	shopSettingExport: '/shoppers/settingExport',
	shopSettingAddgroup: '/shoppers/settingAddgroup',
	shopSettingSort: '/shoppers/settingSort',
	shopSettingAddselect: '/shoppers/settingAddselect',
	shopSettingAddjoin: '/shoppers/settingAddjoin',
	shopSettingAddremove: '/shoppers/settingAddremove',
	
	// 吸粉统计报表
	fansReportList: '/shoppers/fansReportList',
	fansReportExport: '/shoppers/fansReportExport',
	// pk统计报表
	pkReportList: '/shoppers/pkReportList',
	pkReportExport: '/shoppers/pkReportExport'
}
