export default {
  // 订单管理
  searchList: '/order/searchList',
  orderList: '/order/orderList',
  orderInfo: '/order/orderInfo',
  orderUpdate: '/order/orderUpdate',
  orderAdminRemark: '/order/orderRemark',
  orderExport: '/order/orderExport',
  resetOrderCommission: '/order/resetOrderCommission',
  orderAddressChange: '/order/orderAddressChange',
  orderInfoAddress: '/order/orderInfoAddress',
  redFlagOrder: '/order/redFlagOrder',
  OrderInfoUpdate: '/order/OrderInfoUpdate',
  // 发货单管理
  shipmentList: '/order/shipmentList',
  shipmentInfo: '/order/shipmentInfo',
  delieryAdminRemark: '/order/deliveryOrderRemark',
  shipmentInfo: '/order/shipmentInfo',
  deliveryExport: '/order/deliveryExport',
  // 获取快递公司列表
  shippingSimpleList: '/order/shippingSimpleList',
  // 修改物流单号
  changeDelivery: '/order/changeDelivery',
  // 发货操作
  deliverGoods: '/order/deliverGoods',

  // 退货单管理
  returnOrderlist: '/returnOrder/returnOrderList',
  returnOrderRemark: '/returnOrder/returnOrderRemark',
  returnOrderInfo: '/returnOrder/returnOrderInfo',
  returnOrderUpdate: '/returnOrder/returnOrderUpdate',
  returnOrderExport: '/returnOrder/returnOrderExport',
  downloadLogisticsBill: '/order/downloadLogisticsBill',
  uploadLogisticsBill: '/order/uploadLogisticsBill',
  // 退款单管理
  orderRefundInfoList: '/returnOrder/orderRefundInfoList',
  orderRefundRemark: '/returnOrder/orderRefundRemark',
  orderRefundInfo: '/returnOrder/orderRefundInfo',
  orderRefundUpdate: '/returnOrder/orderRefundUpdate',
  orderRefundExport: '/returnOrder/orderRefundExport',
  // 换货单管理
  changeOrderList: '/order/changeOrderList',
  changeOrderMessage: '/order/changeOrderMessage',
  changeOrderUpdate: '/order/changeOrderUpdate',
  // 退货回收站管理
  recycleBinList: '/order/recycleBinList',
  recycleBinInfo: '/order/recycleBinInfo',
  recycleBinRemark: '/order/recycleBinRemark',
  // 退款回收站管理
  refundRecycleBinList: '/order/refundRecycleBinList',
  refundRecycleBinInfo: '/order/refundRecycleBinInfo',
  refundRecycleBinRemark: '/order/refundRecycleBinRemark',
  //快递单号查询
  orderLogistics: '/order/orderLogistics',
  // 手工客服订单
  orderUsersSearch: '/order/orderUsersSearch',
  orderCheckout: '/order/orderCheckout',
  orderConsigneeSave: '/order/orderConsigneeSave',
	orderServiceSave: '/order/orderService',
	getErpPoint:'/order/getErpPoint'
}
