export default {
  // 组件管理
  getPluginsList: '/plugins/list',
  getPluginsLogList: '/plugins/userPluginsLog',
  updateUserPlugin: '/plugins/updateUserPlugin',
  updateBrandPlugin: '/plugins/updateBrandPlugin',
  // 图片上传组件
  uploadImages: '/userImages/upload',
  getImageBase64: '/userImages/getImageBase64',
  // dk添加的，这个接口是包含视频和图片的
  userMaterialList: '/userImages/getList',
  // 旧的命名方式，有时间就把它都替换了
  userImageList: '/userImages/getList',
  // dk添加的，这个接口是包含视频和图片的
  userMaterialRemove: '/userImages/remove',
  // 旧的命名方式，有时间就把它都替换了
  userImageRemove: '/userImages/remove',
  // dk添加的，这个接口是包含视频和图片的
  userUpdateRemark: '/userImages/updateRemark',
  // 旧的命名方式，有时间就把它都替换了
  userImageUpdateRemark: '/userImages/updateRemark',
  // dk添加的，这个接口是包含视频和图片的
  userAddCat: '/userImages/addCat',
  // 旧的命名方式，有时间就把它都替换了
  userImageAddCat: '/userImages/addCat',
  // dk添加的，这个接口是包含视频和图片的
  userUpdateCat: '/userImages/updateCat',
  // 旧的命名方式，有时间就把它都替换了
  userImageUpdateCat: '/userImages/updateCat',
  userRemoveCat: '/userImages/removeCat',

  userImageRemoveCat: '/userImages/removeCat',

  // 标签管理
  tagsList: '/tags/tagsList',
  tagsAdd: '/tags/tagsAdd',
  tagsEdit: '/tags/tagsEdit',
  tagsRemvoe: '/tags/tagsRemove',
  tagMoveCat: '/tags/tagMoveCat',
  tagCatList: '/tags/tagCatList',
  tagCatAdd: '/tags/tagCatAdd',
  tagCatEdit: '/tags/tagCatEdit',
  tagCatRemove: '/tags/tagCatRemove',
  tagRelatedList: '/tags/tagRelatedList',
  tagRelatedAdd: '/tags/tagRelatedAdd',
  tagRelatedRemove: '/tags/tagRelatedRemove',
  tagsTableList: '/tags/tagsTableList',
  tagsTableExport: '/tags/tagsTableExport',
  tagsUserList: '/tags/tagsUserList',

  // 题库组件
  questionBankList: '/questionBank/bankList',
  questionBankAdd: '/questionBank/bankAdd',
  questionBankEdit: '/questionBank/bankEdit',
  questionBankRemove: '/questionBank/bankRemove',
  questionBankUpdateStatus: '/questionBank/bankStatus',
  questionsList: '/questionBank/questionList',
  questionsAdd: '/questionBank/questionAdd',
  questionsEdit: '/questionBank/questionEdit',
  questionsRemove: '/questionBank/questionRemove',
  questionsAnswerRemove: '/questionBank/answerRemove',
  // 大转盘抽奖组件
  turntableList: '/turntable/list',
  turntableEdit: '/turntable/edit',
  turntableInfo: '/turntable/info',
  // 轮播图片
  sliderImageList: '/sliders/sliderImageList',
  sliderImageAdd: '/sliders/sliderImageAdd',
  sliderImageEdit: '/sliders/sliderImageEdit',
  sliderImageUpdateStatus: '/sliders/sliderImageStatus',
  // 直播广场
  liveBroadcastSquareList: '/LiveBroadcastSquare/LiveBroadcastSquareList',
  liveBroadcastSquareInfo: '/LiveBroadcastSquare/LiveBroadcastSquareInfo',
  liveBroadcastSquareSync: '/LiveBroadcastSquare/LiveBroadcastSquareSync',
  liveBroadcastSquareListEdit: '/LiveBroadcastSquare/LiveBroadcastSquareListEdit',
  liveBroadcastSquareListStatus: '/LiveBroadcastSquare/LiveBroadcastSquareListStatus',
  liveBroadcastSquareListRemove: '/LiveBroadcastSquare/LiveBroadcastSquareListRemove',
  liveBroadcastSquareListStick: '/LiveBroadcastSquare/LiveBroadcastSquareListStick',
  // 直播活动
  liveBroadcastActivityList: '/LiveBroadcastActivity/LiveBroadcastActivityList',
  seachLiveRoom: '/LiveBroadcastActivity/SeachLiveRoom',
  liveBroadcastActivityInfo: '/LiveBroadcastActivity/LiveBroadcastActivityInfo',
  liveBroadcastActivityAdd: '/LiveBroadcastActivity/LiveBroadcastActivityAdd',
  liveBroadcastActivityEdit: '/LiveBroadcastActivity/LiveBroadcastActivityEdit',
  // 直播报表
  liveBroadcastTablesList: '/LiveBroadcastTables/LiveBroadcastTablesList',
  liveBroadcastTablesDetailsList: '/LiveBroadcastTables/LiveBroadcastTablesDetailsList',
  liveBroadcastTablesExport: '/LiveBroadcastTables/LiveBroadcastTablesExport',
  liveBroadcastTablesDetailsExport: '/LiveBroadcastTables/LiveBroadcastTablesDetailsExport',
  // 种草社区
  communitySettingCatList: '/CommunitySetting/CommunitySettingCatList',
  communitySettingLableList: '/CommunitySetting/CommunitySettingLableList',
  communitySettingCatAdd: '/CommunitySetting/CommunitySettingCatAdd',
  communitySettingLableAdd: '/CommunitySetting/CommunitySettingLableAdd',
  communitySettingCatEdit: '/CommunitySetting/CommunitySettingCatEdit',
  communitySettingLableEdit: '/CommunitySetting/CommunitySettingLableEdit',
  communitySettingCatRemove: '/CommunitySetting/CommunitySettingCatRemove',
  communitySettingLableRemove: '/CommunitySetting/CommunitySettingLableRemove',
  // 白名单
  communityWhiteBookList: '/CommunityWhiteBook/CommunityWhiteBookList',
  communityWhiteBookJoin: '/CommunityWhiteBook/CommunityWhiteBookJoin',
  communityWhiteBookBatchJoin: '/CommunityWhiteBook/CommunityWhiteBookBatchJoin',
  communityTablesList: '/CommunityTables/CommunityTablesList',
  // 内容列表
  communityContentList: '/CommunityContent/CommunityContentList',
  communityContentInfo: '/CommunityContent/CommunityContentInfo',
  communityContentExport: '/CommunityContent/CommunityContentExport',
  communityContentBatchGo: '/CommunityContent/CommunityContentBatchGo',
  communityContentBatchNotGo: '/CommunityContent/CommunityContentBatchNotGo',
  communityContentStatus: '/CommunityContent/CommunityContentStatus',
  communityContentEdit: '/CommunityContent/CommunityContentEdit',
  communityContentNotGo: '/CommunityContent/CommunityContentNotGo',
  communityContentGo: '/CommunityContent/CommunityContentGo',
  communityGetCatList: '/CommunitySetting/getCatList',
  communityGetLableList: '/CommunitySetting/getLableList',
  // 店铺充值送券
  storeRechargecardCouponsList: '/StoreRechargecardCoupons/StoreRechargecardCouponsList',
  storeRechargecardCouponsInfo: '/StoreRechargecardCoupons/StoreRechargecardCouponsInfo',
  storeRechargecardCouponsAdd: '/StoreRechargecardCoupons/StoreRechargecardCouponsAdd',
  storeRechargecardCouponsEdit: '/StoreRechargecardCoupons/StoreRechargecardCouponsEdit',
  storeRechargecardCouponsRemove: '/StoreRechargecardCoupons/StoreRechargecardCouponsRemove',
  // 店铺充值活动
  storeRechargecardActivityList: '/StoreRechargecardActivity/StoreRechargecardActivityList',
  storeRechargecardActivityInfo: '/StoreRechargecardActivity/StoreRechargecardActivityInfo',
  storeRechargecardActivityAdd: '/StoreRechargecardActivity/StoreRechargecardActivityAdd',
  storeRechargecardActivityEdit: '/StoreRechargecardActivity/StoreRechargecardActivityEdit',
  storeRechargecardActivityStatus: '/StoreRechargecardActivity/StoreRechargecardActivityStatus',
  // 店铺充值卡
  storeRechargecardList: '/StoreRechargecard/StoreRechargecardList',
  storeRechargecardInfo: '/StoreRechargecard/StoreRechargecardInfo',
  getRechargecardList: '/StoreRechargecard/getRechargecardList',
  storeRechargecardAdd: '/StoreRechargecard/StoreRechargecardAdd',
  storeRechargecardEdit: '/StoreRechargecard/StoreRechargecardEdit',
  storeRechargecardUser: '/StoreRechargecard/StoreRechargecardUser'
}
