"use strict";
exports.TEXTNODE = 'TEXTNODE';
exports.COMMENTNODE = 'COMMENTNODE';
exports.NODESTART = 'NODESTART';
exports.NODEEND = 'NODEEND';
exports.NODECLOSESELF = 'NODECLOSESELF';
exports.COMMENTSTART = 'COMMENTSTART';
exports.COMMENTEND = 'COMMENTEND';
