export default {
	
	// 满减活动
	cloudFullReductionGeneralList: '/CloudFullreduction/fullReductionGeneralList',
	cloudFullReductionOverallList: '/CloudFullreduction/fullReductionOverallList',
	cloudFullReductionGeneralRemove: '/CloudFullreduction/fullReductionGeneralRemove',
	cloudFullReductionOverallRemove: '/CloudFullreduction/fullReductionOverallRemove',
	cloudFullReductionGeneralMoneyAdd: '/CloudFullreduction/fullReductionGeneralMoneyAdd',
	cloudFullReductionGeneralPieceAdd: '/CloudFullreduction/fullReductionGeneralPieceAdd',
	cloudFullReductionGeneralInfo: '/CloudFullreduction/fullReductionGeneralInfo',
	cloudFullReductionOverallInfo: '/CloudFullreduction/fullReductionOverallInfo',
	cloudFullReductionGeneralEdit: '/CloudFullreduction/fullReductionGeneralEdit',
	cloudFullReductionOverallEdit: '/CloudFullreduction/fullReductionOverallEdit',
	cloudFullReductionEnableEdit: '/CloudFullreduction/fullReductionEnableEdit',
	cloudFullReductionGeneralSearchq: '/CloudFullreduction/fullReductionGeneralSearchq',
	cloudFullReductionStoreAdd: '/CloudFullreduction/storeAdd',
	cloudFullReductionStoreList: '/CloudFullreduction/storeList',
	cloudFullReductionStoreRemove: '/CloudFullreduction/storeRemove',
	
	// 单品领券活动
	cloudGoodsCouponsActivityList: '/CloudGoodsCouponsActivity/GoodsCouponsActivityList',
	cloudGoodsCouponsActivityAdd: '/CloudGoodsCouponsActivity/GoodsCouponsActivityAdd',
	cloudGoodsCouponsActivityInfo: '/CloudGoodsCouponsActivity/GoodsCouponsActivityInfo',
	cloudGoodsCouponsActivityEdit: '/CloudGoodsCouponsActivity/GoodsCouponsActivityEdit',
	cloudGoodsCouponsActivityRemove: '/CloudGoodsCouponsActivity/GoodsCouponsActivityRemove',
	cloudGoodsCouponsActivityCopy: '/CloudGoodsCouponsActivity/GoodsCouponsActivityCopy',
	cloudBindingGoodsList: '/CloudGoodsCouponsActivity/BindingGoodsList',
	cloudBindingGoodsAdd: '/CloudGoodsCouponsActivity/BindingGoodsAdd',
	cloudBindingGoodsRemove: '/CloudGoodsCouponsActivity/BindingGoodsRemove',
	cloudBindingGoodsBatchRemove: '/CloudGoodsCouponsActivity/BindingGoodsBatchRemove',
	cloudGoodsCouponsStoreAdd: '/CloudGoodsCouponsActivity/storeAdd',
	cloudGoodsCouponsStoreList: '/CloudGoodsCouponsActivity/storeList',
	cloudGoodsCouponsStoreRemove: '/CloudGoodsCouponsActivity/storeRemove',
	
	// 单品推荐活动
	cloudGoodsRecommendList: '/CloudGoodsRecommend/GoodsRecommendList',
	cloudGoodsRecommendAdd: '/CloudGoodsRecommend/GoodsRecommendAdd',
	cloudGoodsRecommendEdit: '/CloudGoodsRecommend/GoodsRecommendEdit',
	cloudGoodsRecommendInfo: '/CloudGoodsRecommend/GoodsRecommendInfo',
	cloudGoodsRecommendRemove: '/CloudGoodsRecommend/GoodsRecommendRemove',
	cloudGoodsRecommendCopy: '/CloudGoodsRecommend/GoodsRecommendCopy',
	cloudBindingRecommendGoodsList: '/CloudGoodsRecommend/BindingGoodsList',
	cloudBindingRecommendGoodsAdd: '/CloudGoodsRecommend/BindingGoodsAdd',
	cloudBindingRecommendGoodsRemove: '/CloudGoodsRecommend/BindingGoodsRemove',
	cloudBindingRecommendGoodsBatchRemove: '/CloudGoodsRecommend/BindingGoodsBatchRemove',
	cloudGoodsRecommendStoreAdd: '/CloudGoodsRecommend/storeAdd',
	cloudGoodsRecommendStoreList: '/CloudGoodsRecommend/storeList',
	cloudGoodsRecommendStoreRemove: '/CloudGoodsRecommend/storeRemove',
}	
	