export default {
  // 活动
  myPageList: '/pages/myPageList',
  createActPage: '/pages/createPage',
  removeActPage: '/pages/removePage',
  getTrashList: '/pages/trashPagesList',
  updateActPage: '/pages/updatePage',
  copyActPage: '/pages/copyPage',
  publishActPage: '/pages/publishPage',
  updateStatusActPage: '/pages/updatePageStatus',
  restoreActPage: '/pages/restorePage',
  downloadWeappQrcode: '/pages/downloadWeappQrcode',
  getPageInfo: '/pages/pageInfo',
  getSceneList: '/pages/sceneList',
  // 砍价活动
  kanActivityList: '/kanActivity/kanList',
  kanActivityAdd: '/kanActivity/kanAdd',
  kanActivityEdit: '/kanActivity/kanEdit',
  kanActivitySort: '/kanActivity/kanSort',
  kanActivityStatus: '/kanActivity/kanStatus',
  kanActivityLog: '/kanActivity/kanLog',
  // 满减活动
  fullReductionGeneralList: '/Fullreduction/fullReductionGeneralList',
  fullReductionOverallList: '/Fullreduction/fullReductionOverallList',
  fullReductionGeneralRemove: '/Fullreduction/fullReductionGeneralRemove',
  fullReductionOverallRemove: '/Fullreduction/fullReductionOverallRemove',
  fullReductionGeneralMoneyAdd: '/Fullreduction/fullReductionGeneralMoneyAdd',
  fullReductionGeneralPieceAdd: '/Fullreduction/fullReductionGeneralPieceAdd',
  fullReductionGeneralInfo: '/Fullreduction/fullReductionGeneralInfo',
  fullReductionOverallInfo: '/Fullreduction/fullReductionOverallInfo',
  fullReductionGeneralEdit: '/Fullreduction/fullReductionGeneralEdit',
  fullReductionOverallEdit: '/Fullreduction/fullReductionOverallEdit',
  fullReductionEnableEdit: '/Fullreduction/fullReductionEnableEdit',
  fullReductionGeneralSearchq: '/Fullreduction/fullReductionGeneralSearchq',
  // 拼团活动
  GroupActivityList: '/GroupActivity/GroupActivityList',
  GroupActivityInfo: '/GroupActivity/GroupActivityInfo',
  GroupActivityAdd: '/GroupActivity/GroupActivityAdd',
  GroupActivityEdit: '/GroupActivity/GroupActivityEdit',
  // 拼团订单
  groupOrderList: '/GroupOrder/groupOrderList',
  groupOrderExport: '/GroupOrder/groupOrderExport',
  groupOrderView: '/GroupOrder/groupOrderView',
  groupOrderRemark: '/GroupOrder/groupOrderRemark',
  // 预售活动
  presaleActivityList: '/PresaleActivity/PresaleActivityList',
  presaleActivityExport: '/PresaleActivity/PresaleActivityExport',
  presaleActivityAdd: '/PresaleActivity/PresaleActivityAdd',
  presaleActivityInfo: '/PresaleActivity/PresaleActivityInfo',
  presaleActivityEdit: '/PresaleActivity/PresaleActivityEdit',
  // 预售订单
  presaleOrderList: '/PresaleOrder/presaleOrderList',
  presaleOrderExport: '/PresaleOrder/presaleOrderExport',
  presaleOrderView: '/PresaleOrder/presaleOrderView',
  // 红包
  redPacketList: '/RedPacket/RedPacketList',
  redPacketRemove: '/RedPacket/RedPacketRemove',
  redPacketAdd: '/RedPacket/RedPacketAdd',
  redAgreementArticle: '/RedPacket/AgreementArticle',
  redPacketRuleEdit: '/RedPacket/RedPacketRuleEdit',
  redPacketEdit: '/RedPacket/RedPacketEdit',
  redPacketSend: '/RedPacket/RedPacketSend',
  redpackSendTag: '/RedPacket/insertRedpackSendTag',
  redPacketAssembly: '/RedPacket/RedPacketAssembly',
  usedRedPacketAssembly: '/RedPacket/usedRedPacketAssembly',
  redPacketAssemblyRemove: '/RedPacket/RedPacketAssemblyRemove',
  usertagManualList: '/RedPacket/UsertagManualList',//获取红包手动标签
  // 店铺自提
  pickupActivityInfo: '/PickupActivity/pickupActivityInfo',
  pickupActivitySave: '/PickupActivity/pickupActivitySave',
  // 购物车推荐
  cartRecommendList: '/CartRecommend/cartRecommendList',
  cartRecommendAdd: '/CartRecommend/cartRecommendAdd',
  cartRecommendEdit: '/CartRecommend/cartRecommendEdit',
  cartRecommendRemove: '/CartRecommend/cartRecommendRemove',
  cartRecommendInfo: '/CartRecommend/cartRecommendInfo',
  // 单品领券活动
  goodsCouponsActivityList: '/GoodsCouponsActivity/GoodsCouponsActivityList',
  goodsCouponsActivityAdd: '/GoodsCouponsActivity/GoodsCouponsActivityAdd',
  goodsCouponsActivityInfo: '/GoodsCouponsActivity/GoodsCouponsActivityInfo',
  goodsCouponsActivityEdit: '/GoodsCouponsActivity/GoodsCouponsActivityEdit',
  goodsCouponsActivityRemove: '/GoodsCouponsActivity/GoodsCouponsActivityRemove',
  goodsCouponsActivityCopy: '/GoodsCouponsActivity/GoodsCouponsActivityCopy',
  bindingGoodsList: '/GoodsCouponsActivity/BindingGoodsList',
  bindingGoodsAdd: '/GoodsCouponsActivity/BindingGoodsAdd',
  BindingGoodsRemove: '/GoodsCouponsActivity/BindingGoodsRemove',
  bindingGoodsBatchRemove: '/GoodsCouponsActivity/BindingGoodsBatchRemove',
  // 单品推荐活动
  goodsRecommendList: '/GoodsRecommend/GoodsRecommendList',
  goodsRecommendAdd: '/GoodsRecommend/GoodsRecommendAdd',
  goodsRecommendEdit: '/GoodsRecommend/GoodsRecommendEdit',
  goodsRecommendInfo: '/GoodsRecommend/GoodsRecommendInfo',
  goodsRecommendRemove: '/GoodsRecommend/GoodsRecommendRemove',
  goodsRecommendCopy: '/GoodsRecommend/GoodsRecommendCopy',
  bindingRecommendGoodsList: '/GoodsRecommend/BindingGoodsList',
  bindingRecommendGoodsAdd: '/GoodsRecommend/BindingGoodsAdd',
  bindingRecommendGoodsRemove: '/GoodsRecommend/BindingGoodsRemove',
  bindingRecommendGoodsBatchRemove: '/GoodsRecommend/BindingGoodsBatchRemove',
  // 视频购物
  videoShoppingList: '/VideoShopping/VideoShoppingList',
  videoShoppingAdd: '/VideoShopping/VideoShoppingAdd',
  videoShoppingEdit: '/VideoShopping/VideoShoppingEdit',
  videoShoppingInfo: '/VideoShopping/VideoShoppingInfo',
  bindingVideoGoodsList: '/VideoShopping/BindingGoodsList',
  bindingVideoGoodsEdit: '/VideoShopping/BindingGoodsEdit',
  videoShoppingSort: '/VideoShopping/VideoShoppingSort',
  videoShoppingRemove: '/VideoShopping/VideoShoppingRemove',
  // 限时特惠
  timeLimitActivityList: '/TimeLimitActivity/TimeLimitActivityList',
  timeLimitActivityAdd: '/TimeLimitActivity/TimeLimitActivityAdd',
  timeLimitActivityEdit: '/TimeLimitActivity/TimeLimitActivityEdit',
  timeLimitActivityEditStatus: '/TimeLimitActivity/TimeLimitActivityEditStatus',
  timeLimitActivityInfo: '/TimeLimitActivity/TimeLimitActivityInfo',
  timeLimitActivityRemove: '/TimeLimitActivity/TimeLimitActivityRemove',
  // 商品搭配套餐
  goodsPackageList: '/GoodsPackage/PackageList',
  packageGoodsList: '/GoodsPackage/PackageGoodsList',
  packageGoodsSort: '/GoodsPackage/PackageGoodsSort',
  packageAdd: '/GoodsPackage/PackageAdd',
  packageInfo: '/GoodsPackage/PackageInfo',
  packageEdit: '/GoodsPackage/PackageEdit',
  packageRemove: '/GoodsPackage/PackageRemove',
  packageGoodsDown: '/GoodsPackage/PackageGoodsDown',
  packageGoodsImport: '/GoodsPackage/PackageGoodsImport',
  packageDown: '/GoodsPackage/PackageDown',
  packageImport: '/GoodsPackage/PackageImport',
  // 微信群管理
  weiXinGroupList: '/WeiXinGroup/WeiXinGroupList',
  weiXinGroupInfo: '/WeiXinGroup/WeiXinGroupInfo',
  weiXinGroupEdit: '/WeiXinGroup/WeiXinGroupEdit',
  weiXinGroupRemove: '/WeiXinGroup/WeiXinGroupRemove',
  weiXinGroupExport: '/WeiXinGroup/WeiXinGroupExport',
  // 签到活动
  signActivityList: '/SignActivity/SignActivityList',
  signActivityAdd: '/SignActivity/SignActivityAdd',
  signActivityStatus: '/SignActivity/SignActivityStatus',
  signActivityInfo: '/SignActivity/SignActivityInfo',
  signActivityEdit: '/SignActivity/SignActivityEdit',
  signActivityExport: '/SignActivity/SignActivityExport',
  // 生日关怀
  birthdayActivityList: '/BirthdayActivity/BirthdayActivityList',
  birthdayActivityAdd: '/BirthdayActivity/BirthdayActivityAdd',
  birthdayActivityStatus: '/BirthdayActivity/BirthdayActivityStatus',
  birthdayActivityInfo: '/BirthdayActivity/BirthdayActivityInfo',
  birthdayActivitySend: '/BirthdayActivity/BirthdayActivitySend',
  birthdayActivityEdit: '/BirthdayActivity/BirthdayActivityEdit',
  birthdayActivityRemove: '/BirthdayActivity/BirthdayActivityRemove',
  // 福报
  birthdayItemList: '/BirthdayItem/BirthdayItemList',
  birthdayItemAdd: '/BirthdayItem/BirthdayItemAdd',
  birthdayItemInfo: '/BirthdayItem/BirthdayItemInfo',
  birthdayItemEdit: '/BirthdayItem/BirthdayItemEdit',
  birthdayItemRemove: '/BirthdayItem/BirthdayItemRemove',
  // 礼包
  couponsBagRefundList: '/CouponsBagRefund/CouponsBagRefundList',
  couponsBagRefundExport: '/CouponsBagRefund/CouponsBagRefundExport',
  // 礼包活动
  couponsBagActivityList: '/CouponsBagActivity/CouponsBagActivityList',
  couponsBagActivityAdd: '/CouponsBagActivity/CouponsBagActivityAdd',
  couponsBagActivityInfo: '/CouponsBagActivity/CouponsBagActivityInfo',
  couponsBagActivityEdit: '/CouponsBagActivity/CouponsBagActivityEdit',
  couponsBagActivityRemove: '/CouponsBagActivity/CouponsBagActivityRemove',
  couponsBagActivityResultsList: '/CouponsBagActivity/CouponsBagActivityResultsList',
  couponsBagActivityResultsExport: '/CouponsBagActivity/CouponsBagActivityResultsExport',
  couponsBagActivityResultsDetail: '/CouponsBagActivity/CouponsBagActivityResultsDetail',
  couponsBagActivityResultsDetailExport: '/CouponsBagActivity/CouponsBagActivityResultsDetailExport',
  // 注册营销
  RegisterRuleGiveInfo: '/RegisterRule/RegisterRuleGiveInfo',
  RegisterRuleGiveSave: '/RegisterRule/RegisterRuleGiveSave',
  registerRebateList: '/RegisterRule/RegisterRebateList',
  registerRebateAdd: '/RegisterRule/RegisterRebateAdd',
  registerRebateEdit: '/RegisterRule/RegisterRebateEdit',
  registerRebateRemove: '/RegisterRule/RegisterRebateRemove',
  registerRebateStatus: '/RegisterRule/RegisterRebateStatus',
  inviteRebateList: '/RegisterRule/InviteRebateList',
  inviteRebateAdd: '/RegisterRule/InviteRebateAdd',
  inviteRebateEdit: '/RegisterRule/InviteRebateEdit',
  inviteRebateRemove: '/RegisterRule/InviteRebateRemove',
  // 大礼包
  registerActivityList: '/RegisterActivity/RegisterActivityList',
  registerActivityInfo: '/RegisterActivity/RegisterActivityInfo',
  registerActivityAdd: '/RegisterActivity/RegisterActivityAdd',
  registerActivityEdit: '/RegisterActivity/RegisterActivityEdit',
  registerActivityStatus: '/RegisterActivity/RegisterActivityStatus',
  registerActivityQrcodeList: '/RegisterActivity/RegisterActivityQrcodeList',
  registerActivityRecord: '/RegisterActivity/RegisterActivityRecord',
  registerActivityRecordExport: '/RegisterActivity/RegisterActivityRecordExport',
  // 弹窗广告
  popupAdvertList: '/PopupAdvert/PopupAdvertList',
  popupAdvertInfo: '/PopupAdvert/PopupAdvertInfo',
  popupAdvertAdd: '/PopupAdvert/PopupAdvertAdd',
  popupAdvertEdit: '/PopupAdvert/PopupAdvertEdit',
  popupAdvertStatus: '/PopupAdvert/PopupAdvertStatus',
  popupAdvertRemove: '/PopupAdvert/PopupAdvertRemove',
  // 资产
  popupAdvertRemindList: '/PopupAdvert/PopupAdvertRemindList',
  popupAdvertRemindInfo: '/PopupAdvert/PopupAdvertRemindInfo',
  popupAdvertRemindAdd: '/PopupAdvert/PopupAdvertRemindAdd',
  popupAdvertRemindEdit: '/PopupAdvert/PopupAdvertRemindEdit',
  popupAdvertRemindStatus: '/PopupAdvert/PopupAdvertRemindStatus',
  popupAdvertRemindRemove: '/PopupAdvert/PopupAdvertRemindRemove',
  // 积分商城
  integralGoodsList: '/IntegralGoods/IntegralGoodsList',
  integralGoodsInfo: '/IntegralGoods/IntegralGoodsInfo',
  integralGoodsAdd: '/IntegralGoods/IntegralGoodsAdd',
  integralGoodsEdit: '/IntegralGoods/IntegralGoodsEdit',
  integralGoodsSort: '/IntegralGoods/IntegralGoodsSort',
  // 积分换卷
  intergralCouponsList: '/IntergralCoupons/IntergralCouponsList',
  intergralCouponsInfo: '/IntergralCoupons/IntergralCouponsInfo',
  intergralCouponsAdd: '/IntergralCoupons/IntergralCouponsAdd',
  intergralCouponsEdit: '/IntergralCoupons/IntergralCouponsEdit',
  //兑换记录
  exchangeLogGoodsList: '/ExchangeLog/ExchangeLogGoodsList',
  exchangeLogGoodsExport: '/ExchangeLog/ExchangeLogGoodsExport',
  exchangeLogCouponsList: '/ExchangeLog/ExchangeLogCouponsList',
  exchangeLogCouponsExport: '/ExchangeLog/ExchangeLogCouponsExport',
  // 砍价活动
  bargainActivityList: '/BargainActivity/BargainActivityList',
  bargainActivityAdd: '/BargainActivity/BargainActivityAdd',
  bargainActivityEdit: '/BargainActivity/BargainActivityEdit',
  bargainActivityInfo: '/BargainActivity/BargainActivityInfo',
  bargainActivitySet: '/BargainActivity/BargainActivitySet',
  bargainActivityData: '/BargainActivity/BargainActivityData',
  // 砍价订单
  bargainOrderList: '/BargainOrder/BargainOrderList',
  bargainOrderInfo: '/BargainOrder/BargainOrderInfo',
  bargainReportList: '/BargainReport/BargainReportList',
  bargainReportExport: '/BargainReport/BargainReportExport',
  // 秒杀分组
  seckillGroupList: '/SeckillGroup/SeckillGroupList',
  seckillGroupStatus: '/SeckillGroup/SeckillGroupStatus',
  seckillGroupAdd: '/SeckillGroup/SeckillGroupAdd',
  seckillGroupEdit: '/SeckillGroup/SeckillGroupEdit',
  seckillGroupRemove: '/SeckillGroup/SeckillGroupRemove',
  // 秒杀订单
  seckillOrderList: '/SeckillOrder/SeckillOrderList',
  seckillOrderInfo: '/SeckillOrder/SeckillOrderInfo',
  // 秒杀活动
  seckillActivityList: '/SeckillActivity/SeckillActivityList',
  seckillActivityAdd: '/SeckillActivity/SeckillActivityAdd',
  seckillActivityEdit: '/SeckillActivity/SeckillActivityEdit',
  seckillActivityInfo: '/SeckillActivity/SeckillActivityInfo',
  seckillActivityRemove: '/SeckillActivity/SeckillActivityRemove',
  seckillActivityData: '/SeckillActivity/SeckillActivityData',
  seckillActivityInitialData: '/SeckillActivity/SeckillActivityInitialData',
  seckillActivityAdvertInfo: '/SeckillActivity/SeckillActivityAdvertInfo',
  // 抽奖活动
	MatrixLotteryType: '/MatrixLotteryActivity/LotteryType', // 活动类型
	MatrixLotteryActivityType:'/MatrixLotteryActivity/LotteryActivityType', // 活动模板
  MatrixLotteryActivityList: '/MatrixLotteryActivity/LotteryActivityList',
  MatrixLotteryActivityInfo: '/MatrixLotteryActivity/LotteryActivityInfo',
  MatrixLotteryActivityAdd: '/MatrixLotteryActivity/LotteryActivityAdd',
  MatrixLotteryActivityEdit: '/MatrixLotteryActivity/LotteryActivityEdit',
  MatrixLotteryActivityRemove: '/MatrixLotteryActivity/LotteryActivityRemove',
  //中奖纪录
  MatrixLotteryLogList: '/MatrixLotteryLog/LotteryLogList',
  MatrixLotteryLogExport: '/MatrixLotteryLog/LotteryLogExport',
  MatrixLotteryLogViewDetails: '/MatrixLotteryLog/LotteryLogViewDetails',
  MatrixLotteryLogDistributionExport: '/MatrixLotteryLog/LotteryLogDistributionExport',
  MatrixLotteryLogViewDetailsExport: '/MatrixLotteryLog/LotteryLogViewDetailsExport',
  // 抽奖模板
  lotteryTemplateList: '/LotteryTemplate/LotteryTemplateList',
  lotteryTemplateAdd: '/LotteryTemplate/LotteryTemplateAdd',
  lotteryTemplateEdit: '/LotteryTemplate/LotteryTemplateEdit',
  lotteryTemplateRemove: '/LotteryTemplate/LotteryTemplateRemove',
  // 中奖订单
  MatrixLotteryOrderList: '/MatrixLotteryOrder/LotteryOrderList',
  MatrixLotteryOrderExport: '/MatrixLotteryOrder/LotteryOrderExport',
  MatrixLotteryOrderData: '/MatrixLotteryOrder/LotteryOrderData',
	// 分享规则
	MatrixSharingRulesList:'/MatrixSharingRules/SharingRulesList',
	MatrixSharingRulesInfo:'/MatrixSharingRules/SharingRulesInfo',
	MatrixSharingRulesAdd:'/MatrixSharingRules/SharingRulesAdd',
	MatrixSharingRulesEdit:'/MatrixSharingRules/SharingRulesEdit',
	MatrixSharingRulesRemove:'/MatrixSharingRules/SharingRulesRemove',
	MatrixSharingRulesDetails:'/MatrixSharingRules/SharingRulesDetails',
	MatrixSharingRulesDetailsExport:'/MatrixSharingRules/SharingRulesDetailsExport',
	//优惠券列表
	MatrixPrizeBonusList:'/MatrixBonus/BonusList',
	MatrixPrizeBonusAdd:'/MatrixBonus/BonusAdd',
	MatrixPrizeBonusEdit:'/MatrixBonus/BonusEdit',
	MatrixPrizeBonusRemove:'/MatrixBonus/BonusRemove',
	MatrixPrizeBonusExport:'/MatrixBonus/BonusExport',
	MatrixPrizeBonusTpl:'/MatrixBonus/BonusTpl',
	MatrixPrizeBonusImport:'/MatrixBonus/BonusImport',
	MatrixPrizeBonusBatch:'/MatrixBonus/BonusBatch',
	//优惠券列表
	MatrixBonusElement:'/MatrixBonus/BonusElement',
	//实物列表
	MatrixPrizeGoodsList:'/MatrixGoods/GoodsList',
	MatrixPrizeGoodsAdd:'/MatrixGoods/GoodsAdd',
	MatrixPrizeGoodsEdit: '/MatrixGoods/GoodsEdit',
	MatrixPrizeGoodsRemove:'/MatrixGoods/GoodsRemove',
	MatrixPrizeGoodsExport:'/MatrixGoods/GoodsExport',
	MatrixPrizeGoodsTpl:'/MatrixGoods/GoodsTpl',
	MatrixPrizeGoodsImport:'/MatrixGoods/GoodsImport',
	MatrixPrizeGoodsBatch:'/MatrixGoods/GoodsBatch',
	//商品列表
	MatrixGoodsElement:'/MatrixGoods/GoodsElement'
}
