export default {
  // 订单管理
  MatrixOrderSearchList: '/MatrixOrder/searchList',
  MatrixOrderList: '/MatrixOrder/orderList',
  MatrixOrderInfo: '/MatrixOrder/orderInfo',
  orderUpdate: '/order/orderUpdate',
  orderAdminRemark: '/order/orderRemark',
  MatrixOrderExport: '/MatrixOrder/orderExport',
  resetOrderCommission: '/order/resetOrderCommission',
  MatrixOrderAddressChange: '/MatrixOrder/orderAddressChange',
  orderInfoAddress: '/order/orderInfoAddress',
  redFlagOrder: '/order/redFlagOrder',
  MatrixOrderInfoUpdate: '/MatrixOrder/OrderInfoUpdate',
  // 发货单管理
  MatrixOrderShipmentList: '/MatrixOrder/shipmentList',
  MatrixOrderShipmentInfo: '/MatrixOrder/shipmentInfo',
  delieryAdminRemark: '/order/deliveryOrderRemark',
  shipmentInfo: '/order/shipmentInfo',
  MatrixOrderDeliveryExport: '/MatrixOrder/deliveryExport',
  // 获取快递公司列表
  MatrixOrderShippingSimpleList: '/MatrixOrder/shippingSimpleList',
  // 修改物流单号
  MatrixOrderChangeDelivery: '/MatrixOrder/changeDelivery',
  // 发货操作
  MatrixOrderDeliverGoods: '/MatrixOrder/deliverGoods',

  // 退货单管理
  returnOrderlist: '/returnOrder/returnOrderList',
  returnOrderRemark: '/returnOrder/returnOrderRemark',
  returnOrderInfo: '/returnOrder/returnOrderInfo',
  returnOrderUpdate: '/returnOrder/returnOrderUpdate',
  returnOrderExport: '/returnOrder/returnOrderExport',
  downloadLogisticsBill: '/order/downloadLogisticsBill',
  uploadLogisticsBill: '/order/uploadLogisticsBill',
  // 退款单管理
  orderRefundInfoList: '/returnOrder/orderRefundInfoList',
  orderRefundRemark: '/returnOrder/orderRefundRemark',
  orderRefundInfo: '/returnOrder/orderRefundInfo',
  orderRefundUpdate: '/returnOrder/orderRefundUpdate',
  orderRefundExport: '/returnOrder/orderRefundExport',
  // 换货单管理
  changeOrderList: '/order/changeOrderList',
  changeOrderMessage: '/order/changeOrderMessage',
  changeOrderUpdate: '/order/changeOrderUpdate',
  // 回收站管理
  recycleBinList: '/order/recycleBinList',
  recycleBinInfo: '/order/recycleBinInfo',
  recycleBinRemark: '/order/recycleBinRemark',
  //快递单号查询
  orderLogistics: '/order/orderLogistics',
  // 手工客服订单
  orderUsersSearch: '/order/orderUsersSearch',
  orderConsigneeSave: '/order/orderConsigneeSave'
}
