export default {
	CloudTodayVisitView: '/CloudVisitStatistics/TodayVisitView',
	CloudTodayVisitExport: '/CloudVisitStatistics/TodayVisitExport',
	CloudHistoryVisitView: '/CloudVisitStatistics/HistoryVisitView',
	CloudHistoryVisitExport: '/CloudVisitStatistics/HistoryVisitExport',
	CloudPageVisitView: '/CloudVisitStatistics/PageVisitView',
	CloudPageVisitExport:'/CloudVisitStatistics/PageVisitExport',
	CloudGoodsVisitView:'/CloudVisitStatistics/GoodsVisitView',
	CloudGoodsVisitExport:'/CloudVisitStatistics/GoodsVisitExport',
	CloudBehaviorVisitView: '/CloudVisitStatistics/BehaviorVisitView',
	CloudBehaviorVisitExport: '/CloudVisitStatistics/BehaviorVisitExport',
	CloudSalesStatsView:'/CloudSalesStatistics/SalesStatsView',
	CloudSalesStatsExport:'/CloudSalesStatistics/SalesStatsExport',
	CloudSalesDetailView: '/CloudSalesStatistics/SalesDetailView',
	CloudSalesDetailExport:'/CloudSalesStatistics/SalesDetailExport',
	CloudUserTotalView:'/CloudUserStatistics/UserTotalView',
	CloudUserTotalExport:'/CloudUserStatistics/UserTotalExport',
	CloudUserDynamicView:'/CloudUserStatistics/UserDynamicView',
	CloudUserDynamicExport:'/CloudUserStatistics/UserDynamicExport',
	CloudUserPlatformView:'/CloudUserStatistics/UserPlatformView'
}
