export const ShareChannel= { 
  1007: { type: "card" },//"单人聊天小程序卡片",
  1008: { type: "card" },//"群聊会话小程序卡片",
  1011: { type: "qrcode" },//"扫描二维码",
  1012: { type: "qrcode" },//"长按图片识别二维码",
  1013: { type: "qrcode" },//"扫描手机相册中选取的二维码",
  1025: { type: "qrcode" },//"扫描一维码",
  1031: { type: "qrcode" },//"长按识别一维码",
  1032: { type: "qrcode" },//"扫描手机相册中选取的一维码",
  1036: { type: "card" },//"App 分享消息卡片",
  1044: { type: "card" },//"带 shareTicket 的小程序消息卡片",
  1047: { type: "qrcode" },//"扫描小程序码", 
  1048: { type: "qrcode" },//"长按图片识别小程序码",
  1049: { type: "qrcode" },//"扫描手机相册中选取的小程序码",
  1072: { type: "qrcode" },//"二维码收款页面",
  1073: { type: "card" },//"客服消息列表下发的小程序消息卡片",
  1074: { type: "card" },//"公众号会话下发的小程序消息卡片",
  1096: { type: "chat" },//"聊天记录",
}